# Generated by Django 4.2.7 on 2023-11-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("implants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyberware",
            name="year_in_school",
            field=models.CharField(
                choices=[("FR", "Freshman"), ("SO", "Sophomore")],
                default="FR",
                max_length=2,
            ),
        ),
    ]
