# Generated by Django 4.2.7 on 2023-11-26 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implants', '0003_remove_cyberware_year_in_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberware',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Емкость'),
        ),
        migrations.AddField(
            model_name='cyberware',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bio_category',
            name='category',
            field=models.CharField(max_length=25, verbose_name='Категория тела'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='Characteristic',
            field=models.CharField(choices=[('BODY', 'Сила'), ('REFLEX', 'Реакция'), ('TECHNICK', 'Техника'), ('COOL', 'Холоднокровие'), ('INTELLIGENCE', 'Нетраннер')], default='BODY', max_length=12, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='implants.bio_category', verbose_name='Категория тела'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='photo',
            field=models.ImageField(upload_to='illustration/cyberware/', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Характеристика'),
        ),
    ]
