# Generated by Django 4.2.7 on 2023-11-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implants', '0004_cyberware_capacity_cyberware_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25, verbose_name='Категория сайта')),
            ],
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
    ]
