# Generated by Django 4.2.7 on 2023-11-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implants', '0007_remove_cyberware_title_bio_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberware',
            name='category',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
    ]
