# Generated by Django 4.2.7 on 2023-11-27 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("implants", "0008_alter_cyberware_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cyberware",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="implants.bio_category",
                verbose_name="Категория тела",
            ),
        ),
    ]
