# Generated by Django 4.2.7 on 2023-11-27 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("implants", "0009_alter_cyberware_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyberware",
            name="bio_category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="implants.bio_category",
                verbose_name="Категория тела",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cyberware",
            name="category",
            field=models.CharField(
                default="Some text", max_length=25, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="menu_category",
            name="category",
            field=models.CharField(
                default="Some text", max_length=25, verbose_name="Название"
            ),
        ),
    ]
