# Generated by Django 4.2.7 on 2023-11-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("implants", "0011_auto_category_clothes_category_items_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cyberware_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=25, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        default="Some text", max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "href",
                    models.CharField(
                        default="implants", max_length=25, verbose_name="Гиперссылка"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="illustration/Menu_preview/",
                        verbose_name="Миниатюра",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=25, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        default="Some text", max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "href",
                    models.CharField(
                        default="implants", max_length=25, verbose_name="Гиперссылка"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="illustration/vehicle/", verbose_name="Иллюстрация"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступно"),
                ),
                (
                    "max_speed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Максимальная скорость"
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=25, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        default="Some text", max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "href",
                    models.CharField(
                        default="implants", max_length=25, verbose_name="Гиперссылка"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="illustration/weapon/", verbose_name="Иллюстрация"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступно"),
                ),
                ("damage", models.PositiveIntegerField(default=0, verbose_name="Урон")),
                (
                    "load_capacity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Вместимость обоимы"
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="transport",
            name="auto_category",
        ),
        migrations.RemoveField(
            model_name="cyberware",
            name="bio_category",
        ),
        migrations.AddField(
            model_name="auto_category",
            name="href",
            field=models.CharField(
                default="implants", max_length=25, verbose_name="Гиперссылка"
            ),
        ),
        migrations.AddField(
            model_name="auto_category",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to="illustration/Menu_preview/",
                verbose_name="Миниатюра",
            ),
        ),
        migrations.AddField(
            model_name="clothes_category",
            name="href",
            field=models.CharField(
                default="implants", max_length=25, verbose_name="Гиперссылка"
            ),
        ),
        migrations.AddField(
            model_name="clothes_category",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to="illustration/Menu_preview/",
                verbose_name="Миниатюра",
            ),
        ),
        migrations.AddField(
            model_name="cyberware",
            name="href",
            field=models.CharField(
                default="implants", max_length=25, verbose_name="Гиперссылка"
            ),
        ),
        migrations.AddField(
            model_name="items_category",
            name="href",
            field=models.CharField(
                default="implants", max_length=25, verbose_name="Гиперссылка"
            ),
        ),
        migrations.AddField(
            model_name="items_category",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to="illustration/Menu_preview/",
                verbose_name="Миниатюра",
            ),
        ),
        migrations.AddField(
            model_name="menu_category",
            name="href",
            field=models.CharField(
                default="implants", max_length=25, verbose_name="Гиперссылка"
            ),
        ),
        migrations.AddField(
            model_name="weapon_category",
            name="href",
            field=models.CharField(
                default="implants", max_length=25, verbose_name="Гиперссылка"
            ),
        ),
        migrations.AddField(
            model_name="weapon_category",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to="illustration/Menu_preview/",
                verbose_name="Миниатюра",
            ),
        ),
        migrations.DeleteModel(
            name="Bio_category",
        ),
        migrations.DeleteModel(
            name="Transport",
        ),
        migrations.AddField(
            model_name="weapon",
            name="weapon_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="implants.weapon_category",
                verbose_name="Категория оружия",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="auto_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="implants.auto_category",
                verbose_name="Тип авто",
            ),
        ),
        migrations.AddField(
            model_name="cyberware",
            name="cyberware_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="implants.cyberware_category",
                verbose_name="Категория тела",
            ),
        ),
    ]
